# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask==1.1.2
        pip install pyyaml==5.3.1
        pip install nltk==3.5
        pip install pyjson==1.3.0
        pip install pandas==1.1.4
        pip install requests==2.25.0
        pip install pytest==6.1.2
        pip install emoji==0.6.0
        pip install textblob==0.15.3
        python test/install_nltk.py
    - name: Test with pytest
      run: |
        pytest test -v
